const DISPLAY_ALERT = 'DISPLAY_ALERT';
const CLEAR_ALERT = 'CLEAR_ALERT';
const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
const LOGOUT_USER = 'LOGOUT_USER';

const API_OPERATION_BEGIN = 'API_OPERATION_BEGIN';
const API_OPERATION_END = 'API_OPERATION_END';

const AUTHENTICATE_USER = 'AUTHENTICATE_USER';

export {
  DISPLAY_ALERT,
  CLEAR_ALERT,
  TOGGLE_SIDEBAR,
  LOGOUT_USER,
  API_OPERATION_BEGIN,
  API_OPERATION_END,
  AUTHENTICATE_USER,
};
