const DISPLAY_ALERT = 'DISPLAY_ALERT';
const CLEAR_ALERT = 'CLEAR_ALERT';

const AUTH_USER_BEGIN = 'AUTH_USER_BEGIN';
const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
const AUTH_USER_ERROR = 'AUTH_USER_ERROR';

const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
const LOGOUT_USER = 'LOGOUT_USER';

export {
  DISPLAY_ALERT,
  CLEAR_ALERT,
  AUTH_USER_BEGIN,
  AUTH_USER_SUCCESS,
  AUTH_USER_ERROR,
  TOGGLE_SIDEBAR,
  LOGOUT_USER
};

